name: Create and Upload Modpack Release

on:
  push:
    branches: [ main ]
    paths:
      # Modpack content changes (trigger releases)
      - 'config/**'          # Mod configurations (PATCH)
      - 'scripts/**'         # CraftTweaker scripts (PATCH)
      - 'shaderpacks/**'     # Shader packs (PATCH)
      - 'modrinth.index.json' # Mod manifest (MINOR for mod changes, PATCH for config)
      - 'mod_overrides.conf' # URL overrides (PATCH)
      - 'options.txt'        # Client settings (PATCH)
      - 'servers.dat'        # Server list (PATCH)
      # Note: mods/** excluded from Git but monitored by build system
      # Infrastructure files (docs, README, build scripts, etc.) are excluded
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        # Install required tools
        sudo apt-get update
        sudo apt-get install -y jq curl wget
        npm install -g modrinth
        
    - name: Download mods and build modpack
      id: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        PROJECT_ID: ${{ vars.MODRINTH_PROJECT_ID }}
      run: |
        echo "- Downloading mods and building modpack from manifest..."
        
        # Set environment variables for build script
        export GITHUB_REPO="${{ github.repository }}"
        export MODRINTH_PROJECT="${{ vars.MODRINTH_PROJECT_ID }}"
        export STRICT_EXTERNAL_DOWNLOADS="true"
        
        # Create mods directory if it doesn't exist
        mkdir -p mods
        
        # Download mods based on existing manifest (if it exists) for faster build
        if [ -f "modrinth.index.json" ]; then
          echo "- Pre-downloading mods from existing manifest for faster build..."
          while IFS= read -r url; do
            if [ -n "$url" ] && [ "$url" != "null" ]; then
              filename=$(basename "$url")
              if [ ! -f "mods/$filename" ]; then
                echo "  Downloading: $filename"
                curl -L -o "mods/$filename" "$url" 2>/dev/null || echo "    Failed to download $filename"
              fi
            fi
          done < <(jq -r '.files[]?.downloads[]?' modrinth.index.json 2>/dev/null | head -200)
        fi
        
        # Make build script executable
        chmod +x build.sh
        
        # Run build script to generate fresh .mrpack from manifest
        echo "- Running build script to generate modpack..."
        
        # Get current version from manifest for version bump logic
        CURRENT_VERSION=$(jq -r '.versionId' modrinth.index.json)
        echo "+ Current version in manifest: $CURRENT_VERSION"
        
        # Smart version detection based on changed files
        echo "- Analyzing changes for version bump..."
        
        # Get the last release tag
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "+ Last release tag: $LAST_TAG"
        
        # Check what files changed since last release
        if [ "$LAST_TAG" != "v0.0.0" ]; then
          CHANGED_FILES=$(git diff --name-only "$LAST_TAG" HEAD || echo "")
        else
          CHANGED_FILES=$(git ls-files)
        fi
        
        echo "+ Changed files:"
        echo "$CHANGED_FILES" | sed 's/^/  /'
        
        # Determine version bump type
        BUMP_TYPE="patch"  # default
        
        if echo "$CHANGED_FILES" | grep -q "modrinth.index.json"; then
          # Check if this is a mod addition/removal (minor) or just config change (patch)
          if git show "$LAST_TAG:modrinth.index.json" 2>/dev/null | jq -r '.files | length' 2>/dev/null > /tmp/old_count && \
             jq -r '.files | length' modrinth.index.json > /tmp/new_count; then
            OLD_COUNT=$(cat /tmp/old_count)
            NEW_COUNT=$(cat /tmp/new_count)
            if [ "$OLD_COUNT" != "$NEW_COUNT" ]; then
              BUMP_TYPE="minor"
              echo "+ Detected mod count change: $OLD_COUNT -> $NEW_COUNT (minor bump)"
            fi
          fi
        fi
        
        if echo "$CHANGED_FILES" | grep -qE "^(config|scripts|shaderpacks)/"; then
          echo "+ Detected configuration changes (patch bump)"
        fi
        
        # Generate new version
        BASE_VERSION=$(echo "$CURRENT_VERSION" | sed 's/^v//')
        IFS='.' read -r major minor patch <<< "$BASE_VERSION"
        
        case "$BUMP_TYPE" in
          "major") NEW_VERSION="$((major + 1)).0.0" ;;
          "minor") NEW_VERSION="$major.$((minor + 1)).0" ;;
          "patch") NEW_VERSION="$major.$minor.$((patch + 1))" ;;
        esac
        
        echo "+ Version bump: $CURRENT_VERSION -> $NEW_VERSION ($BUMP_TYPE)"
        
        # Run build script with version override
        ./build.sh --version "$NEW_VERSION"
        
        # Verify build output
        MRPACK_FILE=$(find . -name "*.mrpack" -type f | head -1)
        if [ -z "$MRPACK_FILE" ]; then
          echo "ERROR: Build script failed to create .mrpack file!"
          exit 1
        fi
        echo "+ Successfully built: $MRPACK_FILE"
        
        # Verify manifest was generated
        if [ ! -f "modrinth.index.json" ]; then
          echo "ERROR: Build script failed to generate modrinth.index.json!"
          exit 1
        fi
        echo "+ Successfully generated: modrinth.index.json"
        
        # Get version from generated manifest
        NEW_VERSION=$(jq -r '.versionId' modrinth.index.json)
        echo "+ Generated version: $NEW_VERSION"
        
        # Check if changelog was generated
        if [ -f "CHANGELOG.md" ]; then
          echo "changelog_file=CHANGELOG.md" >> $GITHUB_OUTPUT
          echo "+ Found generated changelog: CHANGELOG.md"
        fi
        
        # Output for next steps
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "mrpack_file=$MRPACK_FILE" >> $GITHUB_OUTPUT
      
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION="${{ steps.build.outputs.new_version }}"
        MRPACK_FILE="${{ steps.build.outputs.mrpack_file }}"
        
        echo "- Creating GitHub release for version $VERSION..."
        
        # Create release notes
        if [ -f "${{ steps.build.outputs.changelog_file }}" ]; then
          echo "- Using generated changelog for GitHub release..."
          RELEASE_NOTES=$(cat "${{ steps.build.outputs.changelog_file }}")
        else
          echo "- Using default release notes..."
          RELEASE_NOTES="## Survival Not Guaranteed v$VERSION
        
        ****Modpack Release** - Ready for download and installation
        
        ### - What's New
        - Latest mod configurations and updates
        - External download optimization (100% mirror coverage)
        - Automatic server integration included
        - Compatible with Minecraft 1.21.1, NeoForge 21.1.180+
        
        ### - Installation
        1. Download the \`.mrpack\` file below
        2. Import into Modrinth App, PrismLauncher, or compatible launcher
        3. Launch and enjoy!
        
        ### - Server Access
        The modpack automatically adds our community server to your multiplayer list:
        - **Server**: survival-not-guaranteed.modrinth.gg
        - **No manual setup required**
        
        ### - Technical Details
        - **143 mods** with 100% external downloads
        - **Optimized performance** with smart mod resolution
        - **~100% size reduction** (758KB vs 2GB+)
        - **Multi-platform support** (Modrinth + CurseForge mirrors)"
        fi
        
        # Create the release
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{
            \"tag_name\": \"v$VERSION\",
            \"name\": \"Survival Not Guaranteed v$VERSION\",
            \"body\": $(echo "$RELEASE_NOTES" | jq -Rs .),
            \"draft\": false,
            \"prerelease\": false
          }" \
          "https://api.github.com/repos/${{ github.repository }}/releases"
        
        # Get the release ID
        RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/v$VERSION" | \
          jq -r '.id')
        
        echo "- Uploading .mrpack file to release..."
        echo "Release ID: $RELEASE_ID"
        echo "MRPACK file: $MRPACK_FILE"
        
        # Get the filename for the asset and URL encode it
        ASSET_NAME=$(basename "$MRPACK_FILE")
        # URL encode spaces and special characters
        ASSET_NAME_ENCODED=$(echo "$ASSET_NAME" | sed 's/ /%20/g')
        echo "Asset name: $ASSET_NAME"
        echo "Asset name (URL encoded): $ASSET_NAME_ENCODED"
        
        # Upload the .mrpack file with proper URL encoding
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary "@$MRPACK_FILE" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=$ASSET_NAME_ENCODED"
        
        echo "+ GitHub release created successfully!"
        
    - name: Upload to Modrinth
      if: ${{ vars.MODRINTH_PROJECT_ID != '' }}
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        PROJECT_ID: ${{ vars.MODRINTH_PROJECT_ID }}
      run: |
        VERSION="${{ steps.build.outputs.new_version }}"
        MRPACK_FILE="${{ steps.build.outputs.mrpack_file }}"
        
        echo "- Enhanced Modrinth sync and upload process..."
        
        # Function to upload to Modrinth
        upload_to_modrinth() {
          local file_path="$1"
          local version="$2"
          local changelog="$3"
          
          echo "- Uploading $version to Modrinth..."
          
          # Create a more robust JSON-safe changelog
          local json_safe_changelog=$(echo "$changelog" | \
            sed 's/\\/\\\\/g' | \
            sed 's/"/\\"/g' | \
            sed 's/\t/\\t/g' | \
            sed 's/\r/\\r/g' | \
            sed 's/\n/\\n/g' | \
            head -c 4000)
          
          # Get the actual project ID from the project slug if needed
          local actual_project_id="$PROJECT_ID"
          if [[ "$PROJECT_ID" == *"-"* ]]; then
            echo "- Converting project slug to project ID..."
            local project_response=$(curl -s "https://api.modrinth.com/v2/project/$PROJECT_ID" 2>/dev/null || echo "")
            if echo "$project_response" | jq -e '.id' >/dev/null 2>&1; then
              actual_project_id=$(echo "$project_response" | jq -r '.id')
              echo "+ Found project ID: $actual_project_id"
            else
              echo "- FAILED: Failed to resolve project slug to ID"
              return 1
            fi
          fi
          
          # Create JSON data using jq to ensure proper escaping
          jq -n \
            --arg name "Survival Not Guaranteed v$version" \
            --arg version_number "$version" \
            --arg changelog "$json_safe_changelog" \
            --arg project_id "$actual_project_id" \
            '{
              "name": $name,
              "version_number": $version_number,
              "changelog": $changelog,
              "dependencies": [],
              "game_versions": ["1.21.1"],
              "version_type": "release",
              "loaders": ["neoforge"],
              "featured": true,
              "project_id": $project_id,
              "file_parts": ["mrpack-file"]
            }' > /tmp/modrinth_data.json
          
          # Debug: Show the JSON being sent (truncated for readability)
          echo "- JSON being sent to Modrinth:"
          cat /tmp/modrinth_data.json | jq -c . | head -c 500
          echo "..."
          echo ""
          
          # Upload using the JSON file
          local response=$(curl -X POST "https://api.modrinth.com/v2/version" \
            -H "Authorization: $MODRINTH_TOKEN" \
            -H "Content-Type: multipart/form-data" \
            -F "data=@/tmp/modrinth_data.json" \
            -F "mrpack-file=@$file_path" 2>/dev/null || echo "")
          
          if echo "$response" | jq -e '.id' >/dev/null 2>&1; then
            echo "+ Successfully uploaded $version to Modrinth"
            return 0
          else
            echo "- FAILED: Failed to upload $version to Modrinth"
            echo "Response: $response"
            return 1
          fi
        }
        
        # Check if version already exists
        echo "- Checking if version $VERSION exists on Modrinth..."
        EXISTING_VERSION=$(curl -s -H "Authorization: $MODRINTH_TOKEN" \
          "https://api.modrinth.com/v2/project/$PROJECT_ID/version/$VERSION" 2>/dev/null || echo "")
        
        if echo "$EXISTING_VERSION" | jq -e '.id' >/dev/null 2>&1; then
          echo "WARNING: Version $VERSION already exists on Modrinth, skipping upload"
          exit 0
        else
          echo "+ Version $VERSION is new, proceeding with upload..."
        fi
        
        # Create changelog
        if [ -f "${{ steps.build.outputs.changelog_file }}" ]; then
          echo "- Using generated changelog from build script..."
          CHANGELOG=$(cat "${{ steps.build.outputs.changelog_file }}")
          echo "+ Generated changelog loaded ($(echo "$CHANGELOG" | wc -c) chars)"
        else
          echo "- Using default changelog..."
          CHANGELOG="Survival Not Guaranteed v$VERSION - Automated release with latest modpack changes. Features multi-platform mod support (Modrinth + CurseForge), mirror URL redundancy, and smart mod resolution. Minecraft 1.21.1, NeoForge 21.1.180+. Download and import into Modrinth App, PrismLauncher, or other compatible launcher."
        fi
        
        # Upload to Modrinth
        if upload_to_modrinth "$MRPACK_FILE" "$VERSION" "$CHANGELOG"; then
          echo "- Successfully uploaded to Modrinth!"
        else
          echo "- FAILED: Failed to upload to Modrinth"
          exit 1
        fi
        
    - name: Commit and push version update
      run: |
        VERSION="${{ steps.build.outputs.new_version }}"
        
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Note: We don't commit the .mrpack file - it's built on-demand by CI
        # We only track the source files (configs, scripts, etc.) that define the modpack
        
        # Check if there are changes to commit (there shouldn't be any since we build from manifest)
        if git diff --quiet && git diff --cached --quiet; then
          echo "No changes to commit - workflow builds from existing manifest"
          echo "+ Version $VERSION built and released successfully from manifest"
          exit 0
        else
          echo "WARNING: Unexpected changes detected during CI build:"
          git status --porcelain
          echo "The above changes were not committed to maintain clean repository state"
        fi
