name: Create and Upload Modpack Release

on:
  push:
    branches: [ main ]
    paths:
      - 'config/**'
      - 'mods/**'
      - 'minecraft/config/**'
      - 'minecraft/scripts/**'
      - 'minecraft/shaderpacks/**'
      - 'minecraft/resourcepacks/**'
      - 'minecraft/servers.dat'
      - 'scripts/**'
      - 'shaderpacks/**'
      - 'resourcepacks/**'
      - 'modrinth.index.json'
      - 'pack.toml'
      - 'mod_overrides.conf'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install -g modrinth
        
    - name: Analyze changes and determine version bump
      id: version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        PROJECT_ID: ${{ vars.MODRINTH_PROJECT_ID }}
      run: |
        echo "- Using build script's version detection logic..."
        
        # Let the build script handle version detection
        chmod +x build.sh
        
        # Run build script to get the version (it will detect and increment properly)
        ./build.sh
        
        # Extract version from generated manifest
        if [ -f "modrinth.index.json" ]; then
          VERSION=$(jq -r '.versionId' modrinth.index.json)
          echo "Build script determined version: $VERSION"
        else
          echo "ERROR: No modrinth.index.json found after build"
          exit 1
        fi
        
        # Output for next steps
        echo "new_version=$VERSION" >> $GITHUB_OUTPUT
        
        # Find the generated .mrpack file
        MRPACK_FILE=$(find . -name "*.mrpack" -type f | head -1)
        if [ -z "$MRPACK_FILE" ]; then
          echo "- FAILED: No .mrpack file found!"
          exit 1
        fi
        
        echo "+ Found .mrpack file: $MRPACK_FILE"
        echo "mrpack_file=$MRPACK_FILE" >> $GITHUB_OUTPUT
        
        # Check if changelog was generated
        if [ -f "CHANGELOG.md" ]; then
          echo "changelog_file=CHANGELOG.md" >> $GITHUB_OUTPUT
          echo "+ Found generated changelog: CHANGELOG.md"
        else
          echo "+ No changelog generated, will use default"
        fi
      
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION="${{ steps.version.outputs.new_version }}"
        MRPACK_FILE="${{ steps.version.outputs.mrpack_file }}"
        
        echo "- Creating GitHub release for version $VERSION..."
        
        # Create release notes
        if [ -f "${{ steps.version.outputs.changelog_file }}" ]; then
          echo "- Using generated changelog for GitHub release..."
          RELEASE_NOTES=$(cat "${{ steps.version.outputs.changelog_file }}")
        else
          echo "- Using default release notes..."
          RELEASE_NOTES="## Survival Not Guaranteed v$VERSION
        
        ****Modpack Release** - Ready for download and installation
        
        ### - What's New
        - Latest mod configurations and updates
        - External download optimization (100% mirror coverage)
        - Automatic server integration included
        - Compatible with Minecraft 1.21.1, NeoForge 21.1.180+
        
        ### - Installation
        1. Download the \`.mrpack\` file below
        2. Import into Modrinth App, PrismLauncher, or compatible launcher
        3. Launch and enjoy!
        
        ### - Server Access
        The modpack automatically adds our community server to your multiplayer list:
        - **Server**: survival-not-guaranteed.modrinth.gg
        - **No manual setup required**
        
        ### - Technical Details
        - **143 mods** with 100% external downloads
        - **Optimized performance** with smart mod resolution
        - **~100% size reduction** (758KB vs 2GB+)
        - **Multi-platform support** (Modrinth + CurseForge mirrors)"
        fi
        
        # Create the release
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{
            \"tag_name\": \"v$VERSION\",
            \"name\": \"Survival Not Guaranteed v$VERSION\",
            \"body\": $(echo "$RELEASE_NOTES" | jq -Rs .),
            \"draft\": false,
            \"prerelease\": false
          }" \
          "https://api.github.com/repos/${{ github.repository }}/releases"
        
        # Get the release ID
        RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/v$VERSION" | \
          jq -r '.id')
        
        echo "- Uploading .mrpack file to release..."
        echo "Release ID: $RELEASE_ID"
        echo "MRPACK file: $MRPACK_FILE"
        
        # Get the filename for the asset and URL encode it
        ASSET_NAME=$(basename "$MRPACK_FILE")
        # URL encode spaces and special characters
        ASSET_NAME_ENCODED=$(echo "$ASSET_NAME" | sed 's/ /%20/g')
        echo "Asset name: $ASSET_NAME"
        echo "Asset name (URL encoded): $ASSET_NAME_ENCODED"
        
        # Upload the .mrpack file with proper URL encoding
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary "@$MRPACK_FILE" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=$ASSET_NAME_ENCODED"
        
        echo "+ GitHub release created successfully!"
        
    - name: Upload to Modrinth
      if: ${{ vars.MODRINTH_PROJECT_ID != '' }}
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        PROJECT_ID: ${{ vars.MODRINTH_PROJECT_ID }}
      run: |
        VERSION="${{ steps.version.outputs.new_version }}"
        MRPACK_FILE="${{ steps.version.outputs.mrpack_file }}"
        
        echo "- Enhanced Modrinth sync and upload process..."
        
        # Function to upload to Modrinth
        upload_to_modrinth() {
          local file_path="$1"
          local version="$2"
          local changelog="$3"
          
          echo "- Uploading $version to Modrinth..."
          
          # Create a more robust JSON-safe changelog
          local json_safe_changelog=$(echo "$changelog" | \
            sed 's/\\/\\\\/g' | \
            sed 's/"/\\"/g' | \
            sed 's/\t/\\t/g' | \
            sed 's/\r/\\r/g' | \
            sed 's/\n/\\n/g' | \
            head -c 4000)
          
          # Get the actual project ID from the project slug if needed
          local actual_project_id="$PROJECT_ID"
          if [[ "$PROJECT_ID" == *"-"* ]]; then
            echo "- Converting project slug to project ID..."
            local project_response=$(curl -s "https://api.modrinth.com/v2/project/$PROJECT_ID" 2>/dev/null || echo "")
            if echo "$project_response" | jq -e '.id' >/dev/null 2>&1; then
              actual_project_id=$(echo "$project_response" | jq -r '.id')
              echo "+ Found project ID: $actual_project_id"
            else
              echo "- FAILED: Failed to resolve project slug to ID"
              return 1
            fi
          fi
          
          # Create JSON data using jq to ensure proper escaping
          jq -n \
            --arg name "Survival Not Guaranteed v$version" \
            --arg version_number "$version" \
            --arg changelog "$json_safe_changelog" \
            --arg project_id "$actual_project_id" \
            '{
              "name": $name,
              "version_number": $version_number,
              "changelog": $changelog,
              "dependencies": [],
              "game_versions": ["1.21.1"],
              "version_type": "release",
              "loaders": ["neoforge"],
              "featured": true,
              "project_id": $project_id,
              "file_parts": ["mrpack-file"]
            }' > /tmp/modrinth_data.json
          
          # Debug: Show the JSON being sent (truncated for readability)
          echo "- JSON being sent to Modrinth:"
          cat /tmp/modrinth_data.json | jq -c . | head -c 500
          echo "..."
          echo ""
          
          # Upload using the JSON file
          local response=$(curl -X POST "https://api.modrinth.com/v2/version" \
            -H "Authorization: $MODRINTH_TOKEN" \
            -H "Content-Type: multipart/form-data" \
            -F "data=@/tmp/modrinth_data.json" \
            -F "mrpack-file=@$file_path" 2>/dev/null || echo "")
          
          if echo "$response" | jq -e '.id' >/dev/null 2>&1; then
            echo "+ Successfully uploaded $version to Modrinth"
            return 0
          else
            echo "- FAILED: Failed to upload $version to Modrinth"
            echo "Response: $response"
            return 1
          fi
        }
        
        # Check if version already exists
        echo "- Checking if version $VERSION exists on Modrinth..."
        EXISTING_VERSION=$(curl -s -H "Authorization: $MODRINTH_TOKEN" \
          "https://api.modrinth.com/v2/project/$PROJECT_ID/version/$VERSION" 2>/dev/null || echo "")
        
        if echo "$EXISTING_VERSION" | jq -e '.id' >/dev/null 2>&1; then
          echo "WARNING: Version $VERSION already exists on Modrinth, skipping upload"
          exit 0
        else
          echo "+ Version $VERSION is new, proceeding with upload..."
        fi
        
        # Create changelog
        if [ -f "${{ steps.version.outputs.changelog_file }}" ]; then
          echo "- Using generated changelog from build script..."
          CHANGELOG=$(cat "${{ steps.version.outputs.changelog_file }}")
          echo "+ Generated changelog loaded ($(echo "$CHANGELOG" | wc -c) chars)"
        else
          echo "- Using default changelog..."
          CHANGELOG="Survival Not Guaranteed v$VERSION - Automated release with latest modpack changes. Features multi-platform mod support (Modrinth + CurseForge), mirror URL redundancy, and smart mod resolution. Minecraft 1.21.1, NeoForge 21.1.180+. Download and import into Modrinth App, PrismLauncher, or other compatible launcher."
        fi
        
        # Upload to Modrinth
        if upload_to_modrinth "$MRPACK_FILE" "$VERSION" "$CHANGELOG"; then
          echo "- Successfully uploaded to Modrinth!"
        else
          echo "- FAILED: Failed to upload to Modrinth"
          exit 1
        fi
        
    - name: Commit and push version update
      run: |
        VERSION="${{ steps.version.outputs.new_version }}"
        
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes to commit
        if git diff --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Commit changes
        git add modrinth.index.json
        git commit -m "Update version to $VERSION

        - Automated version bump from GitHub Actions
        - Updated modrinth.index.json version field
        - Release $VERSION created and uploaded to platforms"
        
        # Push changes
        git push origin main
        
        echo "+ Version update committed and pushed"
